shop/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, SuccessTemplateView, СancledTemplateView, OrderListview, OrderDetailView

app_name = 'orders'

urlpatterns = [
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('order_success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order_canceled/', СancledTemplateView.as_view(), name='order_canceled'),
    path('orders/', OrderListview.as_view(), name='orders'),
    path('detail_order/<int:pk>/', OrderDetailView.as_view(), name='order_detail')

]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from orders.views import stripe_webhook_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('webhook/stripe/',stripe_webhook_view,name='stripe_webhook')
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

shop/orders/models.py
from django.db import models
from users.models import User
from django.conf import settings
from products.models import Product, Cart


class Order(models.Model):
    objects = None
    CREATED = 1
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    CANCELED = 4
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On way'),
        (DELIVERED, 'Delivered'),
        (CANCELED, 'Canceled'),
    )
    initiator = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    total_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    address = models.CharField(max_length=250, default='')
    basket_history = models.JSONField(default=dict)
    status = models.CharField(max_length=20, choices=STATUSES, default=CREATED)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.initiator.email} | {self.status}'

    def update_after_payment(self):
        baskets = Cart.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_cart_price': float(baskets.total_cart_price()),
        }
        baskets.delete()
        self.save()

shop/orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ivan'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ivanov'}))
    address = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Russian, street, Lenina 1 d.1'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'ivan@gmail.com'}))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

shop/orders/views.py
from http import HTTPStatus
import stripe
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, TemplateView, DetailView
from django.views.generic.list import ListView
from common.Mixins import TitleMixin
from orders.forms import OrderForm
from products.models import Product, Cart
from shop import settings
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'Store - Спасибо за заказ'


class СancledTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/cancled.html'
    title = 'Store - Заказ отменен'


class OrderListview(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Store - Заказы'
    queryset = Order.objects.all()
    ordering = ('-id')

    def get_queryset(self):
        queryset = super(OrderListview, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order-detail.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - Заказ #{self.object.id}'
        return context


class OrderCreateView(TitleMixin, CreateView):
    title = 'Shop - order create'
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Cart.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_canceled')),

        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )

        line_items = session.line_items
        # Fulfill the purchase...
        fulfill_order(line_items)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(line_items):
    order_id = int(line_items.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

shop/orders/templates/orders/cancled.html
{% extends 'products/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Order Cancelled</h3>
                    </div>
                    <div class="card-body">
                        <p class="text-center">Your order has been cancelled.</p>
                        <p class="text-center">We apologize for any inconvenience this may have caused. Please feel free to
                            contact us if you have any questions or concerns.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/orders/templates/orders/order-create.html
{% extends 'products/base.html' %}

{% block content %}
<div class="container">
  <h1>Creating Order</h1>
  <form action="{% url 'orders:order_create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.first_name.id_for_label }}">Name</label>
      {{ form.first_name }}
    </div>
    <div class="form-group">
      <label for="{{ form.last_name.id_for_label }}">Last_name</label>
      {{ form.last_name }}
    </div>
    <div class="form-group">
      <label for="{{ form.email.id_for_label }}">Email</label>
      {{ form.email }}
    </div>
    <div class="form-group">
      <label for="{{ form.address.id_for_label }}">Address</label>
      {{ form.address }}
    </div>
    <hr>
    <table class="table table-striped">
            <thead>
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
              </tr>
            </thead>
            <tbody>

              {% for basket in baskets %}
                <tr>
                  <td>{{ basket.product.name }}</td>
                  <td>{{ basket.quantity }}</td>
                  <td>{{ basket.total_item_price }}</td>
                </tr>
              {% endfor %}

            </tbody>
          </table>
          <hr>
          <div class="form-group">
              <span>Total sum</span>
            <strong>{{ baskets.total_cart_price }} $</strong>
          </div>
          <button type="submit" class="btn btn-primary">Submit Order</button>
        </form>
      </div>


{% endblock %}

shop/orders/templates/orders/order-detail.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card mb-4">
        <div class="card-header">
          <h5 class="card-title">Order №{{ object.id }}</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <tbody>
              <tr>
                <th>First_name</th>
                <td>{{ object.first_name }}</td>
              </tr>
              <tr>
                <th>Email</th>
                <td>{{ object.email }}</td>
              </tr>
              <tr>
                <th>Address</th>
                <td>{{ object.address }}</td>
              </tr>
              <tr>
                <th>City</th>
                <td>{{ object.city }}</td>
              </tr>
              <tr>
                <th>Country</th>
                <td>{{ object.country }}</td>
              </tr>

              <tr>
                <th>Data of order</th>
                <td>{{ object.created_at }}</td>
              </tr>
              <tr>
                <th>Total sum of the order</th>
                <td>{{ object.basket_history.total_cart_price|intcomma }}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{{ object.status }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-header">
          <h5 class="card-title">Заказанные товары</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Товар</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Всего</th>
              </tr>
            </thead>
            <tbody>
              {% for item in object.basket_history.purchased_items %}
              <tr>
                <td>{{ item.product_name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price|intcomma }}</td>
                <td>{{ item.sum|intcomma }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mb-4">Orders</h1>
      <hr>
      {% if object_list %}
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Status</th>
              <th scope="col">Created</th>
              <th scope="col">Total</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for order in object_list %}
              <tr>
                <td scope="row">{{ order.id }}</td>
                <td>{{ order.get_status_display }}</td>
                <td>{{ order.created_at|naturaltime }}</td>
                <td>{{ order.basket_history.total_cart_price }}$ </td>
                <td >
                  <a href="{% url 'orders:order_detail' order.id %}">Detail of the order</a>
                </td>

              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>No orders</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

shop/orders/templates/orders/success.html
{% extends 'products/base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto mt-5">
      <div class="card shadow-sm">
        <div class="card-body text-center">
          <i class="fas fa-check-circle fa-3x text-success"></i>
          <h1 class="mt-3">Payment Succeeded</h1>
          <p class="lead">Thank you for your payment.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}