shop/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, SuccessTemplateView, СancledTemplateView, OrderListview, OrderDetailView

app_name = 'orders'

urlpatterns = [
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('order_success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order_canceled/', СancledTemplateView.as_view(), name='order_canceled'),
    path('orders/', OrderListview.as_view(), name='orders'),
    path('detail_order/<int:pk>/', OrderDetailView.as_view(), name='order_detail')

]

shop/products/urls.py
from django.urls import path
from products.views import  about, home_view, contact, product_list, product_detail, add_to_cart

app_name= 'products'

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('product_list', product_list, name='product_list'),
    path('product_detail/<int:id>/', product_detail, name='product_detail'),
    path('product_list_by_category<int:id>/', product_list, name='product_list_by_category'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),

]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from orders.views import stripe_webhook_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('webhook/stripe/',stripe_webhook_view,name='stripe_webhook')
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

shop/users/urls.py
from django.urls import path

from users.views import logout_view, signup, user_login, password_reset_request, profile, delete_from_cart, elit_profile

app_name = 'users'

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('reset-password/', password_reset_request, name="password_reset"),
    path('user_profile/', profile, name='profile'),
    path('delete_from_cart/<int:basket_id>/', delete_from_cart, name='delete_from_cart'),
    path('edit_profile/', elit_profile, name='edit_profile'),
]

shop/products/models.py
import stripe
from django.db import models
from shop import settings
from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = None
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='products', blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    is_featured = models.BooleanField(default=False)
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='USD')
        return stripe_product_price


class BasketQueryset(models.QuerySet):

    def total_cart_price(self):
        return sum(item.total_item_price() for item in self)

    def total_quantity(self):
        return sum(item.quantity for item in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Cart(models.Model):
    objects = BasketQueryset.as_manager()
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='carts')
    quantity = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.email} | продукт:{self.product.name}'

    def total_item_price(self):
        return self.quantity * self.product.price

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.total_item_price())
        }
        return basket_item

shop/products/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from products.models import Product, Category, Cart


def about(request):
    return render(request, 'products/about.html')


def contact(request):
    return render(request, 'products/contact.html')


def home_view(request, ):
    products = Product.objects.filter(is_featured=True)[:3]
    context = {'products': products, }
    return render(request, 'products/index.html', context)


def product_list(request, id=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_featured=True)
    if id:
        category = get_object_or_404(Category, id=id)
        products = products.filter(category=category)
    paginator = Paginator(products, 2)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
    }
    return render(request, 'products/product_list.html', context)


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'products/product_detail.html', {'product': product})


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Cart.objects.get_or_create(user=request.user, product=product)
    if not baskets.exists():
        Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

shop/products/templates/products/about.html
{% extends 'products/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="my-4">About Us</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut leo sit amet massa tristique imperdiet at a tellus. Nunc ut mi euismod, maximus augue et, accumsan nulla. Praesent vel odio sagittis, varius purus id, sollicitudin justo. Sed in urna dignissim, ornare urna nec, sagittis nisl. Nullam ut nisi faucibus, maximus magna sed, lacinia ipsum. Sed vestibulum, urna ac bibendum finibus, sapien ipsum faucibus elit, nec euismod elit elit eget elit. Donec in tellus ac sapien congue venenatis id non urna.</p>
        <p>Phasellus posuere pretium sapien, sed ultricies quam fermentum ac. Nulla gravida nisi est, eget bibendum odio tincidunt vitae. Curabitur ac interdum quam, a varius eros. Nunc id ultrices neque, at fermentum nisi. Aliquam ac varius leo. Donec aliquam efficitur justo. Vivamus sed dolor lacus. Duis at ipsum augue.</p>
      </div>
    </div>
  </div>
{% endblock %}

shop/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'products:home' %}">My Online Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:product_list' %}">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:contact' %}">Contact</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

              <a class="dropdown-item" href="{% url 'users:profile'  %}">Profile</a>

              <a class="dropdown-item" href="{% url 'orders:orders'  %}">Orders</a>

              <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'users:signup' %}">Signup</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNS0QNf"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

shop/products/templates/products/cart.html
{% if baskets %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Cart</h1>
            <div class="text-right">
                <h4>Total price: {{ baskets.total_cart_price }} $</h4>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>Photo</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Description</th>
                    <th>Total</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in baskets %}
                <tr>
                    <td>
                        {% if cart_item.product.photo %}
                        <img src="{{ cart_item.product.photo.url }}" alt="{{ cart_item.product.name }}" width="100">
                        {% else %}
                        <p>No photos</p>
                        {% endif %}
                    </td>
                    <td>{{ cart_item.product.name }}</td>
                    <td>{{ cart_item.product.price }} $</td>
                    <td>{{ cart_item.quantity }}</td>
                    <td>{{ cart_item.product.description }}</td>
                    <td>{{ cart_item.total_item_price }} $</td>
                    <td>
                        <a href="{% url 'users:delete_from_cart' cart_item.id %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Total</h3>
                        <p>Number of items: {{ baskets.total_quantity }}</p>
                        <p>Total price: {{ baskets.total_cart_price }} $</p>

                        <a href="{% url 'orders:order_create' %}" class="btn btn-primary btn-block">Place Order</a>


                    </div>
                </div>
            </div>
            {% else %}
            <div class="alert alert-info">
                <p>Cart is empty</p>
            </div>
        </div>
    </div>
</div>
{% endif %}

shop/products/templates/products/contact.html
{% extends 'products/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="my-4">Contact Us</h1>
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your name">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="Enter your email">
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" rows="5"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

shop/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
  <!-- Hero section -->
  <section class="hero">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <h1>Welcome to our electronic store</h1>
          <p class="lead">Shop our latest collection of electronics at great prices</p>
          <a href="{% url 'products:product_list' %}" class="btn btn-primary">Shop Now</a>
        </div>
        <div class="col-lg-6">
          <img src="{% static 'img/hero.png' %}" alt="Hero image" class="img-fluid">
        </div>
      </div>
    </div>
  </section>

  <!-- Featured products section -->
  <section class="featured-products">
    <div class="container">
      <h2>Featured Products</h2>
      <div class="row">
        {% for product in products %}
          <div class="col-md-4 mb-4">
            <div class="card">
              {% if product.image  %}
              <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top" width="200" height="300">
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url 'products:product_list' %}" class="btn btn-primary">View Product</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock %}

shop/products/templates/products/product_detail.html
{% extends 'products/base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card border-0 shadow-sm">
        <div class="card-body text-center">
          {% if product.image %}
          <img src="{{ product.image.url }}" class="img-fluid mb-3 rounded" alt="{{ product.name }}" width="200" height="300">
          {% endif %}
          <h2 class="mb-3">{{ product.name }}</h2>
          <p class="lead mb-3">{{ product.description }}</p>
          <p class="h4 text-danger font-weight-bold mb-3">Price: {{ product.price }}</p>
          <form action="{% url 'products:add_to_cart' product.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">
              <i class="fas fa-shopping-cart mr-2"></i>Add to Cart
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/products/templates/products/product_list.html
{% extends 'products/base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-3">
        <h1 class="my-4">Categories</h1>
        <div class="list-group">
            {% for c in categories %}
            <a href="{% url 'products:product_list_by_category' c.id %}"
               class="list-group-item{% if category and category.id == c.id %} active{% endif %}">
                {{ c.name }}
            </a>
            {% endfor %}
        </div>
    </div>
    <div class="col-lg-9">
        <div class="row">
            {% for product in products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    {% if product.image %}
                    <a href="{% url 'products:product_detail' product.id %}"><img class="card-img-top"
                                                                                  src="{{ product.image.url }}" alt=""
                                                                                  width="200" height="300"></a>
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a>
                        </h4>
                        <h5>${{ product.price }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="{% url 'products:add_to_cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center">
            {% if products.has_previous %}
            <a href="?page=1" class="page-link">&laquo; First</a>
            <a href="?page={{ products.previous_page_number }}" class="page-link">&lsaquo; Previous</a>
            {% endif %}

            {% for i in products.paginator.page_range %}
            {% if products.number == i %}
            <a href="?page={{ i }}" class="page-link active">{{ i }}</a>
            {% elif i > products.number|add:'-3' and i < products.number|add:'3' %}
            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
            {% endif %}
            {% endfor %}

            {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}" class="page-link">Next &rsaquo;</a>
            <a href="?page={{ products.paginator.num_pages }}" class="page-link">Last &raquo;</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}